[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints={eth="https://eth-sepolia.g.alchemy.com/v2/NAUn7lS4Hq23ITTgeffrV", arb="https://arb-sepolia.g.alchemy.com/v2/NAUn7lS4Hq23ITTgeffrV"}

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@ccip/=lib/ccip/",
    "@chainlink-local/=lib/chainlink-local/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
